import type { Metadata } from "next";
import { Inter, Lobster } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });
const police = Lobster({ 
  subsets: ["latin"],
  variable:"--font-lobster",
weight:"400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${police.className}`} >
      
      <body className={inter.className + "flex justify-center items-center flex-col"}>
        <div className="flex justify-center flex-col items-center max-w-[1450px] w-full"> 
      <Header/>
        {children}
        </div>
        </body>
        
    </html>
  );
}
